name: L6 Governance Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml

      - name: Validate AI ruleset
        run: python scripts/ai/validate_ruleset.py

      - name: Validate state graph
        run: python scripts/ai/validate_state_graph.py

      - name: Schema Check
        run: python scripts/ai/schema_check.py
